log:
  level: ${LOG_LEVEL:debug}
  channel: ${LOG_CHANNEL:stack}
  formatter: json # "null" or "json"

  channels:

    stack:
      channels:
        - single
        - console

    single:
      filename: 'storage/logs/app.log'

    daily:
      filename: 'storage/logs/app.log'
      when: 'midnight'
      interval: 1
      backupCount: 7

    console:
      stream: null

  formatters:
    json:
      # @see https://docs.python.org/3/library/logging.html#logrecord-attributes
      format: '%(message)s %(asctime)s %(levelname)s %(levelno)d %(pathname)s %(lineno)d'
