// @ts-check
// Note: type annotations allow type checking and IDEs autocompletion

const {themes} = require('prism-react-renderer');
const lightCodeTheme = themes.github;
const darkCodeTheme = themes.dracula;

const llmsRootContent = `Equipment is a Python project scaffolding framework for building applications with configuration, dependency injection, logging, database access, queues, scheduling, storage, tests, compilation, and optional FastAPI serving.

Use this file as an LLM-oriented index. For complete offline documentation content, use https://equipment-python.vercel.app/llms-full.txt.

Important constraints:
- Supported Python versions are 3.12, 3.13, and 3.14.
- Equipment projects use unittest, not pytest.
- Generated projects must remain portable across Linux, macOS, and Windows.
- Runtime dependencies are managed from requirements.txt and should not be changed unless dependency upgrades are explicitly requested.
- Website LLM files are generated by docusaurus-plugin-llms during npm run build.`;

const llmsFullRootContent = `Complete LLM-oriented documentation bundle for Equipment.

Equipment is a Python project scaffolding framework. It generates a ready-to-run project with application structure, configuration, dependency injection, logging, SQLAlchemy database access, queues, scheduling, local/S3 storage, unittest-based tests, bytecode compilation support, and an optional FastAPI entry point.

Read this file when you need enough context to build applications using Equipment or maintain the Equipment repository. Preserve Python 3.12, 3.13, and 3.14 support, keep Unix and Windows behavior in mind, and keep README, website docs, and generated LLM outputs consistent.`;

/** @type {import('@docusaurus/types').Config} */
const config = {
    title: "Equipment",
    tagline: "The root of your next python project",
    url: "https://equipment-python.vercel.app",
    baseUrl: "/",
    onBrokenLinks: "throw",
    markdown: {
        hooks: {
            onBrokenMarkdownLinks: "warn",
        },
    },
    favicon: "img/favicon.ico",
    organizationName: "rogervila", // Usually your GitHub org/user name.
    projectName: "equipment", // Usually your repo name.

    presets: [
        [
            "classic",
            /** @type {import('@docusaurus/preset-classic').Options} */
            ({
                docs: {
                    sidebarPath: require.resolve("./sidebars.js"),
                    // Please change this to your repo.
                    editUrl: "https://github.com/rogervila/equipment/tree/main/website/",
                },
                blog: {
                    showReadingTime: true,
                    // Please change this to your repo.
                    editUrl: "https://github.com/rogervila/equipment/tree/main/website/",
                },
                theme: {
                    customCss: require.resolve("./src/css/custom.css"),
                },
            }),
        ],
    ],

    plugins: [
        [
            "docusaurus-plugin-llms",
            {
                title: "Equipment Documentation",
                description: "Documentation for building and maintaining Python applications with Equipment.",
                docsDir: "docs",
                generateLLMsTxt: true,
                generateLLMsFullTxt: true,
                generateMarkdownFiles: true,
                preserveDirectoryStructure: true,
                addMdExtension: true,
                excludeImports: true,
                removeDuplicateHeadings: true,
                includeBlog: false,
                includeOrder: [
                    "intro.md",
                    "getting-started/installation.md",
                    "getting-started/directory-structure.md",
                    "getting-started/common-workflows.md",
                    "features/dependency-injection.md",
                    "features/config.md",
                    "features/database.md",
                    "features/log.md",
                    "features/queue.md",
                    "features/scheduler.md",
                    "features/storage.md",
                    "features/tests.md",
                    "features/compilation.md",
                    "examples/fastapi.md",
                    "reference/cli.md",
                    "reference/environment-variables.md",
                    "reference/maintenance.md",
                ],
                includeUnmatchedLast: true,
                rootContent: llmsRootContent,
                fullRootContent: llmsFullRootContent,
                logLevel: "normal",
            },
        ],
    ],

    themeConfig:
        /** @type {import('@docusaurus/preset-classic').ThemeConfig} */
        ({
            navbar: {
                title: "Equipment",
                logo: {
                    alt: "Equipment Logo",
                    src: "img/logo.svg",
                },
                items: [
                    {
                        type: "doc",
                        docId: "intro",
                        position: "left",
                        label: "Docs",
                    },
                    { to: "/blog", label: "Blog", position: "left" },
                    { to: "/llms.txt", label: "LLMS.txt", position: "left" },
                    { to: "/llms-full.txt", label: "LLMS Full", position: "left" },
                    {
                        href: "https://pypi.org/project/equipment",
                        label: "PyPI",
                        position: "right",
                    },
                    {
                        href: "https://github.com/rogervila/equipment",
                        label: "GitHub",
                        position: "right",
                    },
                ],
            },
            footer: {
                style: "dark",
                links: [
                    {
                        title: "Docs",
                        items: [
                            {
                                label: "Docs",
                                to: "/docs/intro",
                            },
                        ],
                    },
                    {
                        title: "Community",
                        items: [
                            // {
                            //   label: 'Stack Overflow',
                            //   href: 'https://stackoverflow.com/questions/tagged/equipment',
                            // },
                            // {
                            //   label: 'Discord',
                            //   href: 'https://discordapp.com/invite/docusaurus',
                            // },
                            {
                                label: "X",
                                href: "https://x.com/_rogervila",
                            },
                        ],
                    },
                    {
                        title: "More",
                        items: [
                            {
                                label: "Blog",
                                to: "/blog",
                            },
                            {
                                label: "GitHub",
                                href: "https://github.com/rogervila/equipment",
                            },
                        ],
                    },
                ],
                copyright: `Copyright © ${new Date().getFullYear()} Roger Vilà`,
            },
            prism: {
                theme: lightCodeTheme,
                darkTheme: darkCodeTheme,
            },
        }),
};

module.exports = config;
