name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run tests
        run: |
          sudo apt-get install libgeos-dev -y
          export PROJECT_PATH=$(pwd)
          echo $PROJECT_PATH
          ls -lahrt ${PROJECT_PATH}
          python -m pip install --upgrade pip
          pip install coverage runtype wheel twine setuptools
          cd ${PROJECT_PATH}/equipment/framework && pip install -r requirements.txt
          cd ${PROJECT_PATH}/equipment/console && pip install -r requirements.txt
          cd ${PROJECT_PATH}/equipment/project && pip install -r requirements.txt
          cd ${PROJECT_PATH}/equipment/framework && coverage run -m unittest discover
          cd ${PROJECT_PATH}/equipment/console && coverage run -m unittest discover
          cd ${PROJECT_PATH}/equipment/project && coverage run -m unittest discover
      - name: SonarCloud Scan
        if: ${{ matrix.python-version == '3.10'}}
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.SONAR_GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=rogervila-github
            -Dsonar.projectKey=rogervila_equipment
            -Dsonar.sources=.
            -Dsonar.exclusions=**/tests/**
            -Dsonar.test.exclusions=**/tests/**
            -Dsonar.tests=equipment/console/tests/,equipment/framework/tests/,equipment/project/tests/
            -Dsonar.verbose=true
